language: python
sudo: enabled

# Install dependencies.
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt

script:
  # Style checks.
  - for f in $(find . -name '*.py'); do pycodestyle --first $f; done
