sudo: enabled

language: python
python:
  - 3.6

env:
  - PYTHONPATH=.

# Install dependencies.
install:
  - pip3 install --upgrade pip
  - pip3 install -r requirements.txt

script:
  # Tests.
  - python3 -m coverage run --source=. -m run_tests
  - python3 -m coverage xml

  # Train neural network and send results.
  - python3 data/dataset_manipulation/generate_dataset_same_dimensions.py
  - python3 deblurrer/cnn_autoencoder/train.py --run restart | tee output.txt

  - ./slack_file_upload output.txt "#performance-metrics"

  # Style checks.
  - for f in $(find . -name '*.py'); do pycodestyle --first $f; done

after_success:
  - python3 -m codecov --token=a0ba70e0-9134-421f-b423-3aa504d98fa8
