sudo: enabled

language: python
python:
  - 3.6

addons:
    apt:
        packages:
            - sshpass

env:
  - PYTHONPATH=.

# Install dependencies.
install:
  - pip3 install --upgrade pip
  - pip3 install -r requirements.txt
  - pip3 install --pre azure-cli --extra-index-url https://azurecliprod.blob.core.windows.net/edge

script:
  # Tests.
  - python3 -m coverage run --source=. -m run_tests
  - python3 -m coverage xml

  # Style checks.
  - for f in $(find . -name '*.py'); do pycodestyle --first $f; done

after_success:
  - python3 -m codecov --token=a0ba70e0-9134-421f-b423-3aa504d98fa8

  # Upload to azure.
  - az login -u rf1515@ic.ac.uk -p cpOO9506
  - az vm start -g frobenius -n deblurrer
  - sshpass -p cpOO9506Legan ssh zippo@$13.90.101.59 './deblurring/run.sh'
  - az vm stop -g frobenius -n deblurrer
