sudo: enabled

language: python
python:
  - 3.6

# Install dependencies.
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt

script:
  # Style checks.
  - for f in $(find . -name '*.py'); do pycodestyle --first $f; done
  # Train neural network and send results.
  - python3 deblurrer/cnn_denoise_experiment/train.py restart >> output.txt
  - ./slack_file_upload oputput.txt "#tensorboard-logs"
