sudo: enabled

language: python
python:
  - 3.6

# Install dependencies.
install:
  - pip3 install --upgrade pip
  - pip3 install -r requirements.txt

script:
  # Tests.
  - python3 -m coverage run --source=. -m run_tests

  # Train neural network and send results.
  - python3 deblurrer/cnn_autoencoder/train.py --run restart >> output.txt
  - ./slack_file_upload output.txt "#performance-metrics"

  # Style checks.
  - for f in $(find . -name '*.py'); do pycodestyle --first $f; done

after_success:
  - coveralls
